@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json

###

POST http://{{host}}/api/user/login HTTP/1.1
Content-Type: {{contentType}}

{
  "password": "",
  "email": "chrisnguyenaz@gmail.com"
}

###
GET http://{{host}}/api/user/5cb46c4c408effa7cf16d70f HTTP/1.1
Content-Type: {{contentType}}


###
GET http://{{host}}/api/google/key HTTP/1.1
Content-Type: {{contentType}}

###
GET http://{{host}}/api/event/search/?categories=[112]&q=party&location.latitude=&location.longitude=	 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzbmd1eWVuYXpAZ21haWwuY29tIiwidXNlcklkIjoiNWNiNDZjNGM0MDhlZmZhN2NmMTZkNzBmIiwiaWF0IjoxNTU1ODQ2OTY5LCJleHAiOjE1NTU4NTA1Njl9.GyWCJXR0fKoLY4zcdOQMj_anfU1wJHsbf156Pc9gWys