@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json

###

POST http://{{host}}/api/user/login HTTP/1.1
Content-Type: {{contentType}}

{
  "password": "",
  "email": "chrisnguyenaz@gmail.com"
}

###
GET http://{{host}}/api/user/5cb4651fd6b4cca5c2affcb2 HTTP/1.1
Content-Type: {{contentType}}