export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GEO_START = 'GEO_START';
export const GEO_SUCCESS = 'GEO_SUCCESS';
export const GEO_FAIL = 'GEO_FAIL';

// export const USER_PROFILE_START = 'USER_PROFILE_START';
export const USER_CREATE_PROFILE_SUCCESS = 'USER_CREATE_PROFILE_SUCCESS';
export const USER_CREATE_PROFILE_FAIL = 'USER_CREATE_PROFILE_FAIL';

export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_SUCCESS';
